on: push

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Setup app dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: enabling corepack
        run: corepack enable

      - name: Install
        run: pnpm install --frozen-lockfile

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Setup app dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: enabling corepack
        run: corepack enable

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Run prettier
        run: pnpm prettier:check

      - name: Run eslint
        run: pnpm lint

  build:
    name: Build code
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Setup app dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: enabling corepack
        run: corepack enable

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - name: Setup app dependencies
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: enabling corepack
        run: corepack enable

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Unit test
        run: pnpm test
