on: push

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup app dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-node_modules

      - name: Install
        run: yarn install --frozen-lockfile

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup app dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          fail-on-cache-miss: true

      - name: Run prettier
        run: yarn prettier:check

  build:
    name: Build code
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup app dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          fail-on-cache-miss: true

      - name: Build
        run: yarn build
